baseURL: https://sta101-spr23-lane.netlify.app
languageCode: en-us
defaultContentLanguage: en
title: "STA 101 Spring 2023"
theme: "PaperMod"
publishDir: 'public'
#pygmentsCodefences: yes
#pygmentsUseClasses: yes
#rssLimit: 10
# copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
#   4.0 International License.
 enableEmoji: yes
author:
  name: Andrea Lane
# blackfriday: {}
# taxonomies:
#   tag: tags

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: schedule
      name: Schedule
      url: static/schedule/schedule.html
      weight: 20
    - identifier: syllabus
      name: Syllabus
      url: /syllabus
      weight: 30
    - identifier: office hours
      name: Office Hours
      url: https://duke.box.com/s/bfx0fkhlrss4fqguuf6fhrqhswgbsnqu
      weight: 40
    - identifier: practice
      name: Practice
      url: /practice
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production
  
  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
  defaultTheme: dark
  homeInfoParams:
        Title: "STA 101 Spring 2023"
        Content: "Welcome to STA 101: Data Analysis and Statistical Inference"
  # code_copy_button: yes
  # dateform: Jan 2, 2006
  # dateformNum: '2006-01-02'
  # dateformNumTime: 2006-01-02 15:04 -0700
  # dateformShort: Jan 2
  # footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/"
  #   target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # homeSubtitle: Data Analysis and Statistical Inference
  # #justifyContent: no
  # relatedPosts: no
  # # defaultTheme: light
  # # defaultTheme: dark
  # defaultTheme: auto # to switch between dark or light according to browser theme
  socialIcons:
    - name: R
      url: https://cmgr.oit.duke.edu/containers
       #<a class="inline-block" href="#"><img class="" src="{{ (default "Rlogo.svg" ) | relURL }}" alt="mysite" width="26"></a>
    - name: slack
      url: https://sta101spring2023.slack.com
    #- name: github
      #url: https://github.com/fisher-group/sta101
    - name: book
      url: https://openintro-ims.netlify.app/
  #themeColor: '#494f5c'
  #themeColor: '#000000'
  # text search
  
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true 
